name: bread_units_beta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  path: ^1.8.3
  searchfield: ^1.1.7

flutter:
  uses-material-design: true